[package]
name = "chaoschain"
version = "0.1.0"
edition = "2021"

[lib]
name = "chaoschain"
path = "src/lib.rs"

[dependencies]
# General dependencies
async-trait = "0.1"
bytes = "1.9"
color-eyre = "0.6"
derive-where = "1.2"
eyre = "0.6"
libp2p-identity = "0.2"
rand = "0.8"
serde_json = "1.0"
sha3 = "0.10"
tracing = "0.1"
tokio = "1.42"
redb = "2.4.0"

# Add these new dependencies
prost = "0.13"
thiserror = "1.0"

[dependencies.malachitebft-app-channel]
version = "0.0.1"
# This adds the `informalsystems-malachitebft-app-channel` as a dependency, but exposes it
# under `malachitebft_app_channel` instead of its full package name.
git = "ssh://git@github.com/informalsystems/malachite.git"
package = "informalsystems-malachitebft-app-channel"

[dependencies.malachitebft-test]
version = "0.0.1"
git = "ssh://git@github.com/informalsystems/malachite.git"
package = "informalsystems-malachitebft-test"

[dependencies.malachitebft-test-cli]
version = "0.0.1"
git = "ssh://git@github.com/informalsystems/malachite.git"
package = "informalsystems-malachitebft-test-cli"

[dependencies.malachitebft-proto]
version = "0.0.1"
git = "ssh://git@github.com/informalsystems/malachite.git"
package = "informalsystems-malachitebft-proto"
